image:
  #name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  name: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
  #name: hashicorp/terraform:1.1.6
  # entrypoint:
  #   - "/usr/bin/env"
  #   - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Default output file for Terraform plan
variables:
  TF_PLAN: plan.tfplan
  TF_INPUT: 0
  TF_IN_AUTOMATION: yes
  JSON_PLAN_FILE: tfplan.json

cache:
  paths:
    - tests/aws/.terraform
    - tests/bitbucket/.terraform
    - tests/github/.terraform
    - tests/gitlab/.terraform

stages:
  - init
  - validate
  - release

init:
  stage: init
  script:
    - terraform --version

validate-aws:
  stage: validate
  script:
    - echo "pwd is $(pwd)"
    - cd tests/aws
    - terraform init -input=false
    - terraform validate

validate-bb:
  stage: validate
  script:
    - echo "pwd is $(pwd)"
    - cd tests/bitbucket
    - terraform init -input=false
    - terraform validate

validate-gl:
  stage: validate
  script:
    - echo "pwd is $(pwd)"
    - cd tests/gitlab
    - terraform init -input=false
    - terraform validate

validate-gh:
  stage: validate
  script:
    - echo "pwd is $(pwd)"
    - cd tests/github
    - terraform init -input=false
    - terraform validate

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Nothing special to do here"
  release:
    name: "My awesome release"
    description: "another tagged release"
    tag_name: "$CI_COMMIT_TAG"
    milestones:
      - "v0.3"
      - "v0.2"
