image:
  name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

# Default output file for Terraform plan
variables:
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json

cache:
  paths:
    - tests/aws/.terraform
    - tests/bitbucket/.terraform
    - tests/github/.terraform
    - tests/gitlab/.terraform

before_script:
  - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
  - terraform --version

stages:
  - validate
  - validate_bb
  - validate_gh
  - validate_gl

validate:
  stage: validate
  script:
    - echo "pwd is $(pwd)"
    - cd tests/aws
    - terraform init -input=false
    - terraform validate

validate_bb:
  stage: validate_bb
  script:
    - echo "pwd is $(pwd)"
    - cd tests/bitbucket
    - terraform init -input=false
    - terraform validate

validate_gl:
  stage: validate_gl
  script:
    - echo "pwd is $(pwd)"
    - cd tests/gitlab
    - terraform init -input=false
    - terraform validate

validate_gh:
  stage: validate_gh
  script:
    - echo "pwd is $(pwd)"
    - cd tests/github
    - terraform init -input=false
    - terraform validate
