# OpenTofu CI/CD component based pipeline.
# Component: https://gitlab.com/components/opentofu
# Releases & supported component/OpenTofu version combinations:
# https://gitlab.com/components/opentofu/-/releases
# Run one validate job per test directory.
include:
  - project: 'ds_2/ci-templates'
    ref: v3.11.0
    file:
      - '/templates/stages.yaml'
      - '/templates/global-vars.yaml'
      - '/templates/release-marker.yaml'
  - component: $CI_SERVER_FQDN/components/opentofu/validate@4.9.0
    inputs:
      as: validate-aws
      opentofu_version: 1.12.6
      root_dir: tests/aws
  - component: $CI_SERVER_FQDN/components/opentofu/validate@4.9.0
    inputs:
      as: validate-bb
      opentofu_version: 1.12.6
      root_dir: tests/bitbucket
  - component: $CI_SERVER_FQDN/components/opentofu/validate@4.9.0
    inputs:
      as: validate-gl
      opentofu_version: 1.12.6
      root_dir: tests/gitlab
  - component: $CI_SERVER_FQDN/components/opentofu/validate@4.9.0
    inputs:
      as: validate-gh
      opentofu_version: 1.12.6
      root_dir: tests/github
  - component: $CI_SERVER_FQDN/components/opentofu/validate@4.9.0
    inputs:
      as: validate-az
      opentofu_version: 1.12.6
      root_dir: tests/azure

# stages:
#   - validate
#   - release

# release:
#   stage: release
#   image: registry.gitlab.com/gitlab-org/release-cli:latest
#   rules:
#     - if: $CI_COMMIT_TAG
#   script:
#     - echo "Nothing special to do here"
#   release:
#     name: "Release $CI_COMMIT_TAG"
#     description: "Created using the release-cli $EXTRA_DESCRIPTION"
#     tag_name: "$CI_COMMIT_TAG"
#     ref: "$CI_COMMIT_TAG"
#     milestones:
#       - "v0.4"