name: Test Terraform modules

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  test:
    name: test all flows
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 5
      matrix:
        testdir:
          - github
          - gitlab
          - bitbucket
          - azure
          - aws
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - uses: opentofu/setup-opentofu@v1
      - run: pwd
      - name: Fmt check
        working-directory: tests/${{ matrix.testdir }}
        run: tofu fmt-check
        continue-on-error: true
      - name: OpenTofu init
        if: always()
        working-directory: tests/${{ matrix.testdir }}
        run: tofu init -input=false
      - name: Validating
        working-directory: tests/${{ matrix.testdir }}
        run: tofu validate
