name: Test Terraform modules

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  test:
    name: test all flows
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5
      matrix:
        testdir:
          - github
          - gitlab
          - bitbucket
          - azure
          - aws
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - run: cd tests/${{ matrix.testdir }}
      - run: terraform init -input=false
      - run: terraform validate
